services:
  postgres1:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db1
    ports:
      - "5433:5432"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  postgres2:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db2
    ports:
      - "5434:5432"
    volumes:
      - ./init2:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  exporter:
    build:
      context: ..
    env_file: .env
    depends_on:
      postgres1:
        condition: service_healthy
      postgres2:
        condition: service_healthy
    ports:
      - "${EXPORTER_PORT}:${EXPORTER_PORT}"
    volumes:
      - ./queries.json:/app/queries.json:ro
      - ./databases.json:/app/databases.json

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

